### ISSUE TITLE
interaction problem between PVector from Pyrsistent and pykka under Python 3.8

### ISSUE THREAD

**Issue by chemouda** [jodal/pykka#150]
there seems to be a general problem in the interaction between PVector from Pyrsistent and pykka Since Python 3.8, causing  recursion errors of the form:

```python
onsite_1    | Traceback (most recent call last):
onsite_1    |   File "/ems/onsite/main.py", line 49, in <module>
onsite_1    |     _cls_operator = CLSOperator.new(_cls, _notifier)
onsite_1    |   File "/ems/cls/operator.py", line 175, in new
onsite_1    |     actor.update_cls(pvector(ecls)).get() # sync up
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_threading.py", line 55, in get
onsite_1    |     raise exc_value
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_actor.py", line 186, in _actor_loop
onsite_1    |     response = self._handle_receive(envelope.message)
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_actor.py", line 286, in _handle_receive
onsite_1    |     return callee(*message.args, **message.kwargs)
onsite_1    |   File "/ems/cls/operator.py", line 78, in update_cls
onsite_1    |     self.reset_proxies()
onsite_1    |   File "/ems/cls/operator.py", line 95, in reset_proxies
onsite_1    |     self.proxies = [CLSProxy.new(channel(cls)) for cls in self.cls_set]
onsite_1    |   File "/ems/cls/operator.py", line 95, in <listcomp>
onsite_1    |     self.proxies = [CLSProxy.new(channel(cls)) for cls in self.cls_set]
onsite_1    |   File "/ems/cls/operator.py", line 93, in channel
onsite_1    |     return PresentCLSStateChannel.new(_present_cls_state_channel_seal, cls, self.actor_ref.proxy())
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_ref.py", line 170, in proxy
onsite_1    |     return ActorProxy(self)
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_proxy.py", line 124, in __init__
onsite_1    |     self._known_attrs = self._introspect_attributes()
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_proxy.py", line 141, in _introspect_attributes
onsite_1    |     if self._is_self_proxy(attr):
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_proxy.py", line 173, in _is_self_proxy
onsite_1    |     return attr == self
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pyrsistent/_pvector.py", line 81, in __eq__
onsite_1    |     return self is other or (hasattr(other, '__len__') and self._count == len(other)) and compare_pvector(self, other, operator.eq)
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_proxy.py", line 215, in __getattr__
onsite_1    |     if attr_path not in self._known_attrs:
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_proxy.py", line 215, in __getattr__
onsite_1    |     if attr_path not in self._known_attrs:
onsite_1    |   File "/opt/venv/lib/python3.8/site-packages/pykka/_proxy.py", line 215, in __getattr__
onsite_1    |     if attr_path not in self._known_attrs:
onsite_1    |   [Previous line repeated 980 more times]
onsite_1    | RecursionError: maximum recursion depth exceeded
```

Seems like generally the problem does not occur when wrapping PVector as fields

**Comment by jodal** [comment]
I've tried reproducing this, but have failed so far. You say that "generally the problem does not occur when wrapping PVector as fields", but not anything about when the problem *does* occur.

Are you able to provide a runnable example that reproduces the issue?

**Comment by chemouda** [comment]
Versions: Python3.8.10, pyrsistent0.17.3, pykka3.0.1
running the following will reproduces the error
`from pykka import ThreadingActor

from pyrsistent import freeze

class A(ThreadingActor):

    def __init__(self):

        super().__init__()

        self.v = freeze([])
A.start().proxy()`

**Comment by jodal** [comment]
I've set up an environment with the exact same versions:

```
❯ python --version
Python 3.8.10
❯ pip show pyrsistent | grep Version
Version: 0.17.3
❯ pip show pykka | grep Version     
Version: 3.0.1
```

When I'm trying to reproduce everything seems to work as expected:

``` python
❯ python
Python 3.8.10 (default, Jun 29 2021, 09:59:27) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykka import ThreadingActor
>>> from pyrsistent import freeze
>>> class A(ThreadingActor):
...     def __init__(self):
...         super().__init__()
...         self.v = freeze([])
... 
>>> a = A.start().proxy()
>>> a
<ActorProxy for A (urn:uuid:a840849b-c39d-4207-9399-ab996802fe92), attr_path=()>
>>> a.v
<pykka._threading.ThreadingFuture object at 0x7f3a296bbc10>
>>> a.v.get()
pvector([])
>>> 
```

Do you have any idea what I might be missing?

**Comment by chemouda** [comment]
We don't really know what the actual problem was, but updating Pyrsistent to (0.18.0) solved our problem.

**Comment by jodal** [comment]
Thanks for following up!
