### ISSUE TITLE
How can I stop an eventlet actor on Ctrl+C?

### ISSUE THREAD

**Issue by drozzy** [jodal/pykka#49]
So I am trying to move way for ThreadingActors so my system doesn't eat up 50 threads... Decided to go with Eventlet.

How do I handle the "main" file where everything starts up, and when uses sends kill signal or presses Ctrl+C the script stops?

Currently I have my main loop setup with eventlet actors like so (this used to be `time.sleep` with threading actors):

    while True:
        eventlet.sleep(1)

and my signal handler is responsible for stopping all the actors when the application shuts down:

    def signal_handler(s, frame):
        logger.info('You pressed Ctrl+C. Stopping all systems.')
        # Stop all top level actors in reverse order
        poller.stop()
        source_cache.stop()
        harvester.stop()
        linked_store.stop()
        result_store.stop()
        logger.info("All systems stopped.")
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

However, this does not work. Signal handler seems to never execute. Instead I get the error:

          
            Traceback (most recent call last):
          File "c:\Users\drozdyuka\Projects\env\Scripts\harvester-script.py", line 9, in
         <module>
            load_entry_point('ResourceRepositoryNetwork==0.1.9', 'console_scripts', 'har
        vester')()
          File "c:\users\drozdyuka\projects\lpsscf\resourcerepositorynetwork\resourcerep
        ositorynetwork\harvester\harvester_runner.py", line 124, in main
            sleep(1)
          File "c:\Users\drozdyuka\Projects\env\lib\site-packages\eventlet\greenthread.p
        y", line 32, in sleep
            hub.switch()
          File "c:\Users\drozdyuka\Projects\env\lib\site-packages\eventlet\hubs\hub.py",
         line 293, in switch
        
            return self.greenlet.switch()
          File "c:\Users\drozdyuka\Projects\env\lib\site-packages\eventlet\hubs\hub.py",
         line 345, in run
            self.wait(sleep_time)
          File "c:\Users\drozdyuka\Projects\env\lib\site-packages\eventlet\hubs\selects.
        py", line 34, in wait
            time.sleep(seconds)
          File "c:\users\drozdyuka\projects\lpsscf\resourcerepositorynetwork\resourcerep
        ositorynetwork\harvester\harvester_runner.py", line 106, in signal_handler
            poller.stop()
          File "build\bdist.win32\egg\pykka\actor.py", line 511, in stop
          File "build\bdist.win32\egg\pykka\eventlet.py", line 65, in get
          File "build\bdist.win32\egg\pykka\future.py", line 69, in get
          File "build\bdist.win32\egg\pykka\actor.py", line 502, in _stop_result_convert
        er
          File "build\bdist.win32\egg\pykka\eventlet.py", line 79, in get
          File "c:\Users\drozdyuka\Projects\env\lib\site-packages\eventlet\event.py", li
        ne 121, in wait
            return hubs.get_hub().switch()
          File "c:\Users\drozdyuka\Projects\env\lib\site-packages\eventlet\hubs\hub.py",
         line 279, in switch
            assert cur is not self.greenlet, 'Cannot switch to MAINLOOP from MAINLOOP'
        AssertionError: Cannot switch to MAINLOOP from MAINLOOP
        (env) /C/Users/drozdyuka/Projects/lpsscf [hotfix-actors|? 8]

I even tried wrapping the things into exception handlers, but weird things are happening. 

Has anyone had any luck with this?

**Comment by sunyifei83** [comment]
add some code to talk it ....

To stop an actor, you can either call stop() on the actor_ref:

actor_ref.stop()
Or, if an actor wants to stop itself, it can simply do so:

self.stop()
Once an actor has been stopped, it cannot be restarted.
